"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { Chart } from "@/components/Chart";
import { PageHeader } from "@/components/PageHeader";
import { useMe } from "@/lib/useMe";
import {
  api,
  ConnectorFreshness,
  InsightDashboard,
  InsightPanel,
  InsightPin,
  InsightScope,
} from "@/lib/api";

/**
 * Visualizations - curated charts per connected source.
 *
 * Nobody creates a dashboard here. It exists because a connector exists, which
 * is why there is no "new chart" button, no permissions model and no
 * publishing step: a chart aggregates rows this member could already retrieve
 * in prose, scoped to the company or to one space they belong to.
 *
 * Every number came from SQL over `activity_facts`. Nothing on this page is
 * generated by a model, and the empty states are deliberately three different
 * sentences - "nothing connected", "never synced" and "no activity in this
 * window" are three different facts, and collapsing them is what makes a
 * dashboard untrustworthy.
 */

const SOURCE_LABEL: Record<string, string> = {
  notion: "Notion",
  google: "Google Drive",
  slack: "Slack",
  linear: "Linear",
  github: "GitHub",
  forms: "Google Forms",
};

const PERIODS = [
  { key: "week", label: "Weekly" },
  { key: "month", label: "Monthly" },
  { key: "quarter", label: "Quarterly" },
];

function label(provider: string): string {
  return SOURCE_LABEL[provider] ?? provider;
}

function since(iso: string | null): string {
  if (!iso) return "";
  return new Date(iso).toLocaleDateString(undefined, {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

function ago(iso: string | null): string {
  if (!iso) return "never";
  const minutes = Math.round((Date.now() - new Date(iso).getTime()) / 60000);
  if (minutes < 2) return "just now";
  if (minutes < 60) return `${minutes} min ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.round(hours / 24)}d ago`;
}

export default function VisualizationsPage() {
  // Deliberately NOT requireAdmin: a chart aggregates rows this member can
  // already retrieve in prose, so gating it behind admin would be theatre.
  const { me, loading: meLoading } = useMe();
  const [scopes, setScopes] = useState<InsightScope[] | null>(null);
  // "" is the company, matching the server's `workspace_id IS NULL`. A
  // separate "org" sentinel would be a second vocabulary for the same thing.
  const [scope, setScope] = useState("");
  const [period, setPeriod] = useState("month");
  const [dashboard, setDashboard] = useState<InsightDashboard | null>(null);
  const [freshness, setFreshness] = useState<ConnectorFreshness[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // The ask box. One turn, no history: `asked` is the last question's result,
  // replaced rather than appended, because this is a chart request and not a
  // conversation.
  const [question, setQuestion] = useState("");
  const [asking, setAsking] = useState(false);
  const [asked, setAsked] = useState<InsightPanel | null>(null);
  const [askedSpec, setAskedSpec] = useState<{
    metric: string;
    group_by: string | null;
    period: string;
  } | null>(null);
  const [askMessage, setAskMessage] = useState<string | null>(null);
  const [pins, setPins] = useState<InsightPin[]>([]);
  const [pinnedPanels, setPinnedPanels] = useState<InsightPanel[]>([]);

  useEffect(() => {
    api
      .listInsightScopes()
      .then(setScopes)
      .catch(() => setError("Could not load your spaces."));
  }, []);

  const load = useCallback(() => {
    setLoading(true);
    setError(null);
    const id = scope || null;
    Promise.all([
      api.getInsightDashboard(id, period),
      api.getConnectorFreshness(id),
      api.listInsightPins(),
    ])
      .then(([board, fresh, pinned]) => {
        setDashboard(board);
        setFreshness(fresh);
        setPins(pinned);
      })
      .catch((err) =>
        setError(
          err instanceof Error ? err.message : "Could not load these charts.",
        ),
      )
      .finally(() => setLoading(false));
  }, [scope, period]);

  useEffect(load, [load]);

  async function ask(e: React.FormEvent) {
    e.preventDefault();
    const text = question.trim();
    if (!text || asking) return;
    setAsking(true);
    setAskMessage(null);
    try {
      const result = await api.askForChart(text, scope || null);
      if (result.charted) {
        setAsked(result.panel);
        setAskedSpec(result.spec);
      } else {
        // Not an error banner: a refusal that names what IS available is
        // guidance, and styling it as a fault would read as broken.
        setAsked(null);
        setAskedSpec(null);
        setAskMessage(result.message);
      }
    } catch (err) {
      setAskMessage(
        err instanceof Error ? err.message : "Could not work that out.",
      );
    } finally {
      setAsking(false);
    }
  }

  async function pin() {
    if (!askedSpec) return;
    try {
      await api.pinChart(
        askedSpec.metric,
        askedSpec.group_by,
        askedSpec.period,
        scope || null,
      );
      setPins(await api.listInsightPins());
    } catch (err) {
      setAskMessage(err instanceof Error ? err.message : "Could not pin that.");
    }
  }

  async function unpin(pinId: string) {
    try {
      await api.unpinChart(pinId);
      setPins(await api.listInsightPins());
    } catch {
      /* A failed unpin leaves the pin visible, which is the honest state. */
    }
  }

  const alreadyPinned = Boolean(
    askedSpec &&
    pins.some(
      (p) =>
        p.metric === askedSpec.metric &&
        p.period === askedSpec.period &&
        (p.group_by ?? null) === askedSpec.group_by &&
        (p.scope ?? null) === (scope || null),
    ),
  );

  const current = useMemo(
    () => (scopes || []).find((s) => (s.id ?? "") === scope) ?? null,
    [scopes, scope],
  );
  const mySpaces = useMemo(
    () => (scopes || []).filter((s) => s.id !== null),
    [scopes],
  );

  // Panels grouped by connector, so the page reads as "here is Notion, here is
  // Drive" rather than one undifferentiated wall of charts.
  const byProvider = useMemo(() => {
    const groups = new Map<string, InsightDashboard["panels"]>();
    for (const panel of dashboard?.panels || []) {
      const list = groups.get(panel.provider) || [];
      list.push(panel);
      groups.set(panel.provider, list);
    }
    return [...groups.entries()];
  }, [dashboard]);

  const connectedButUnchartable = (current?.providers || []).filter(
    (p) => !(current?.chartable || []).includes(p),
  );

  if (meLoading || !me) {
    return (
      <main className="page">
        <p className="muted">Loading…</p>
      </main>
    );
  }

  return (
    <AppShell me={me}>
      <main className="page-wide stack">
        <PageHeader
          eyebrow="Explore"
          title="Visualizations"
          description="What your connected apps have actually been doing. Every number here is counted from your own data — nothing on this page is written by a model."
        />

        <div className="viz-controls">
          <div className="field">
            <label htmlFor="viz-scope">Where</label>
            <select
              id="viz-scope"
              className="input"
              value={scope}
              onChange={(e) => setScope(e.target.value)}
            >
              {/* Grouped for the same reason the scheduler's picker is: a flat
                list makes the company read as "just another space", which is
                exactly what confused first-time users there. Labelled by
                WHICH APPS get read, never by audience. */}
              <optgroup label="The company's apps">
                <option value="">Company-wide</option>
              </optgroup>
              {mySpaces.length > 0 && (
                <optgroup label="One space's apps">
                  {mySpaces.map((s) => (
                    <option key={s.id} value={s.id ?? ""}>
                      {s.name}
                      {s.providers.length
                        ? ` - ${s.providers.map(label).join(", ")}`
                        : " - nothing connected"}
                    </option>
                  ))}
                </optgroup>
              )}
            </select>
            {scope && (
              <p className="muted viz-hint">
                Reads only {current?.name ?? "this space"}&apos;s own apps,
                never the company&apos;s.
              </p>
            )}
          </div>

          <div className="field">
            <label htmlFor="viz-period">Grouped by</label>
            <div
              className="viz-period"
              role="group"
              aria-labelledby="viz-period"
            >
              {PERIODS.map((p) => (
                <button
                  key={p.key}
                  type="button"
                  className="button button-secondary button-sm"
                  data-active={period === p.key ? "true" : "false"}
                  aria-pressed={period === p.key}
                  onClick={() => setPeriod(p.key)}
                >
                  {p.label}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* The ask box lives INSIDE the section rather than being a second
            chat surface. A separate box would make people guess which one a
            question belongs in, and would split their history. It resolves to
            one of the charts below - the model selects, it never computes. */}
        <form className="card viz-ask" onSubmit={ask}>
          <label htmlFor="viz-ask-input">Ask for a chart</label>
          <div className="viz-ask-row">
            <input
              id="viz-ask-input"
              className="input"
              placeholder="task completion by team"
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              maxLength={400}
              disabled={asking}
            />
            <button
              type="submit"
              className="button"
              disabled={asking || !question.trim()}
            >
              {asking ? "…" : "Show"}
            </button>
          </div>
          <p className="muted viz-hint">
            Picks one of the charts below and applies your filters. It never
            invents a number.
          </p>

          {askMessage && (
            <p className="viz-ask-message" role="status">
              {askMessage}
            </p>
          )}

          {asked && (
            <article className="viz-panel viz-ask-result">
              <header className="viz-panel-head">
                <h3>{asked.title}</h3>
                <button
                  type="button"
                  className="button button-secondary button-sm"
                  onClick={pin}
                  disabled={alreadyPinned}
                >
                  {alreadyPinned ? "Pinned" : "Pin"}
                </button>
              </header>
              {asked.points && asked.points.length > 0 ? (
                <Chart
                  chart={asked.chart}
                  points={asked.points}
                  period={askedSpec?.period || period}
                  unit={asked.unit}
                />
              ) : (
                <p className="muted viz-panel-empty">
                  Nothing recorded for that yet.
                </p>
              )}
              {asked.caveat && (
                <p className="muted viz-panel-caveat">{asked.caveat}</p>
              )}
            </article>
          )}
        </form>

        {pins.length > 0 && (
          <section className="card viz-pins">
            <h2 className="viz-section-title">Pinned</h2>
            <ul className="viz-pin-list">
              {pins.map((p) => (
                <li key={p.id} className="viz-pin">
                  <span>{p.title}</span>
                  <span className="muted">{p.period}</span>
                  <button
                    type="button"
                    className="button button-secondary button-sm"
                    onClick={() => unpin(p.id)}
                  >
                    Remove
                  </button>
                </li>
              ))}
            </ul>
            <p className="muted viz-hint">Only you can see these.</p>
          </section>
        )}

        {error && (
          <div className="banner banner-warn" role="alert">
            {error}
          </div>
        )}

        {/* Freshness first, deliberately. A chart is worthless if nobody can
          tell whether it is current, and `needs_reauth` is called out
          separately because auto-sync skips a dead token entirely - waiting
          will never fix it. */}
        {freshness.length > 0 && (
          <section className="card viz-freshness">
            <h2 className="viz-section-title">Last synced</h2>
            <ul className="viz-fresh-list">
              {freshness.map((c) => (
                <li key={c.provider} className="viz-fresh-row">
                  <strong>{label(c.provider)}</strong>
                  {c.needs_reauth ? (
                    <span className="viz-fresh-bad">
                      Needs reconnecting - not syncing
                    </span>
                  ) : (
                    <span className="muted">{ago(c.last_sync_at)}</span>
                  )}
                </li>
              ))}
            </ul>
          </section>
        )}

        {loading && !dashboard ? (
          <p className="muted">Loading charts…</p>
        ) : !current || current.providers.length === 0 ? (
          <div className="card viz-empty">
            <h2 className="viz-section-title">Nothing connected here yet</h2>
            <p className="muted">
              {scope
                ? "This space has no apps connected, so there is nothing to chart."
                : "Connect Notion, Drive, Slack, Linear or GitHub and charts appear here on the next sync."}
            </p>
            <Link
              href={scope ? `/workspaces/${scope}` : "/admin/sources"}
              className="button"
            >
              Connect an app
            </Link>
          </div>
        ) : byProvider.length === 0 ? (
          <div className="card viz-empty">
            <h2 className="viz-section-title">No charts for these apps yet</h2>
            <p className="muted">
              {connectedButUnchartable.map(label).join(", ")}{" "}
              {connectedButUnchartable.length === 1 ? "is" : "are"} connected,
              but has no charts built yet.
            </p>
          </div>
        ) : (
          byProvider.map(([provider, panels]) => (
            <section key={provider} className="viz-provider">
              <h2 className="viz-section-title">{label(provider)}</h2>
              <div className="viz-grid">
                {panels.map((panel) => (
                  <article key={panel.id} className="card viz-panel">
                    <header className="viz-panel-head">
                      <h3>{panel.title}</h3>
                      {panel.measured_since && (
                        <p className="muted viz-panel-since">
                          Measured since {since(panel.measured_since)}
                        </p>
                      )}
                    </header>

                    {panel.points === null ? (
                      <p className="viz-fresh-bad">
                        This chart could not be loaded.
                      </p>
                    ) : panel.points.length === 0 ? (
                      <p className="muted viz-panel-empty">
                        {freshness.find((f) => f.provider === provider)
                          ?.last_sync_at
                          ? "No activity in this window."
                          : "Waiting for the first sync."}
                      </p>
                    ) : (
                      <Chart
                        chart={panel.chart}
                        points={panel.points}
                        period={dashboard?.period || period}
                        unit={panel.unit}
                      />
                    )}

                    {/* GitHub is read live into facts on a sync, not at page
                      load - so its numbers are as fresh as the last sync, and
                      the freshness panel above says when that was. */}
                    {panel.caveat && (
                      <p className="muted viz-panel-caveat">{panel.caveat}</p>
                    )}
                  </article>
                ))}
              </div>
            </section>
          ))
        )}
      </main>
    </AppShell>
  );
}
